// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGqMaE4JXKoWy5BJnfTb0A4NN6s_9pXew',
    appId: '1:738468842688:web:79692ce95f4e112560b125',
    messagingSenderId: '738468842688',
    projectId: 'flash-app-185ae',
    authDomain: 'flash-app-185ae.firebaseapp.com',
    storageBucket: 'flash-app-185ae.appspot.com',
    measurementId: 'G-WC2PX5JQ4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-XkLKUhZpOmije37evQwn3TBXBric8Ng',
    appId: '1:738468842688:android:fe3c497eab39422e60b125',
    messagingSenderId: '738468842688',
    projectId: 'flash-app-185ae',
    storageBucket: 'flash-app-185ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBYmI0bvgmfca-bFsFXB1szUSkqQYqqW0',
    appId: '1:738468842688:ios:4fd816c6a0313e4660b125',
    messagingSenderId: '738468842688',
    projectId: 'flash-app-185ae',
    storageBucket: 'flash-app-185ae.appspot.com',
    iosClientId: '738468842688-v6hl24udb0v7hi5f9m3kibedgpkpfqmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBYmI0bvgmfca-bFsFXB1szUSkqQYqqW0',
    appId: '1:738468842688:ios:cb58b4bcf486ef1260b125',
    messagingSenderId: '738468842688',
    projectId: 'flash-app-185ae',
    storageBucket: 'flash-app-185ae.appspot.com',
    iosClientId: '738468842688-u0t962en67hf98b89tn00tkndc4fjceq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flash.RunnerTests',
  );
}
